// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_referenceline.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_osi_5freferenceline_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_osi_5freferenceline_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "osi_common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_osi_5freferenceline_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_osi_5freferenceline_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_osi_5freferenceline_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_osi_5freferenceline_2eproto_metadata_getter(int index);
namespace osi3 {
class ReferenceLine;
struct ReferenceLineDefaultTypeInternal;
extern ReferenceLineDefaultTypeInternal _ReferenceLine_default_instance_;
class ReferenceLine_ReferenceLinePoint;
struct ReferenceLine_ReferenceLinePointDefaultTypeInternal;
extern ReferenceLine_ReferenceLinePointDefaultTypeInternal _ReferenceLine_ReferenceLinePoint_default_instance_;
}  // namespace osi3
PROTOBUF_NAMESPACE_OPEN
template<> ::osi3::ReferenceLine* Arena::CreateMaybeMessage<::osi3::ReferenceLine>(Arena*);
template<> ::osi3::ReferenceLine_ReferenceLinePoint* Arena::CreateMaybeMessage<::osi3::ReferenceLine_ReferenceLinePoint>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace osi3 {

// ===================================================================

class ReferenceLine_ReferenceLinePoint PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osi3.ReferenceLine.ReferenceLinePoint) */ {
 public:
  inline ReferenceLine_ReferenceLinePoint() : ReferenceLine_ReferenceLinePoint(nullptr) {}
  virtual ~ReferenceLine_ReferenceLinePoint();
  explicit constexpr ReferenceLine_ReferenceLinePoint(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReferenceLine_ReferenceLinePoint(const ReferenceLine_ReferenceLinePoint& from);
  ReferenceLine_ReferenceLinePoint(ReferenceLine_ReferenceLinePoint&& from) noexcept
    : ReferenceLine_ReferenceLinePoint() {
    *this = ::std::move(from);
  }

  inline ReferenceLine_ReferenceLinePoint& operator=(const ReferenceLine_ReferenceLinePoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReferenceLine_ReferenceLinePoint& operator=(ReferenceLine_ReferenceLinePoint&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReferenceLine_ReferenceLinePoint& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReferenceLine_ReferenceLinePoint* internal_default_instance() {
    return reinterpret_cast<const ReferenceLine_ReferenceLinePoint*>(
               &_ReferenceLine_ReferenceLinePoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReferenceLine_ReferenceLinePoint& a, ReferenceLine_ReferenceLinePoint& b) {
    a.Swap(&b);
  }
  inline void Swap(ReferenceLine_ReferenceLinePoint* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReferenceLine_ReferenceLinePoint* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReferenceLine_ReferenceLinePoint* New() const final {
    return CreateMaybeMessage<ReferenceLine_ReferenceLinePoint>(nullptr);
  }

  ReferenceLine_ReferenceLinePoint* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReferenceLine_ReferenceLinePoint>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReferenceLine_ReferenceLinePoint& from);
  void MergeFrom(const ReferenceLine_ReferenceLinePoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReferenceLine_ReferenceLinePoint* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osi3.ReferenceLine.ReferenceLinePoint";
  }
  protected:
  explicit ReferenceLine_ReferenceLinePoint(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_osi_5freferenceline_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorldPositionFieldNumber = 1,
    kSPositionFieldNumber = 2,
  };
  // .osi3.Vector3d world_position = 1;
  bool has_world_position() const;
  private:
  bool _internal_has_world_position() const;
  public:
  void clear_world_position();
  const ::osi3::Vector3d& world_position() const;
  ::osi3::Vector3d* release_world_position();
  ::osi3::Vector3d* mutable_world_position();
  void set_allocated_world_position(::osi3::Vector3d* world_position);
  private:
  const ::osi3::Vector3d& _internal_world_position() const;
  ::osi3::Vector3d* _internal_mutable_world_position();
  public:
  void unsafe_arena_set_allocated_world_position(
      ::osi3::Vector3d* world_position);
  ::osi3::Vector3d* unsafe_arena_release_world_position();

  // double s_position = 2;
  void clear_s_position();
  double s_position() const;
  void set_s_position(double value);
  private:
  double _internal_s_position() const;
  void _internal_set_s_position(double value);
  public:

  // @@protoc_insertion_point(class_scope:osi3.ReferenceLine.ReferenceLinePoint)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::osi3::Vector3d* world_position_;
  double s_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_osi_5freferenceline_2eproto;
};
// -------------------------------------------------------------------

class ReferenceLine PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:osi3.ReferenceLine) */ {
 public:
  inline ReferenceLine() : ReferenceLine(nullptr) {}
  virtual ~ReferenceLine();
  explicit constexpr ReferenceLine(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReferenceLine(const ReferenceLine& from);
  ReferenceLine(ReferenceLine&& from) noexcept
    : ReferenceLine() {
    *this = ::std::move(from);
  }

  inline ReferenceLine& operator=(const ReferenceLine& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReferenceLine& operator=(ReferenceLine&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReferenceLine& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReferenceLine* internal_default_instance() {
    return reinterpret_cast<const ReferenceLine*>(
               &_ReferenceLine_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReferenceLine& a, ReferenceLine& b) {
    a.Swap(&b);
  }
  inline void Swap(ReferenceLine* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReferenceLine* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReferenceLine* New() const final {
    return CreateMaybeMessage<ReferenceLine>(nullptr);
  }

  ReferenceLine* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReferenceLine>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReferenceLine& from);
  void MergeFrom(const ReferenceLine& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReferenceLine* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "osi3.ReferenceLine";
  }
  protected:
  explicit ReferenceLine(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_osi_5freferenceline_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  typedef ReferenceLine_ReferenceLinePoint ReferenceLinePoint;

  // accessors -------------------------------------------------------

  enum : int {
    kPolyLineFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .osi3.ReferenceLine.ReferenceLinePoint poly_line = 2;
  int poly_line_size() const;
  private:
  int _internal_poly_line_size() const;
  public:
  void clear_poly_line();
  ::osi3::ReferenceLine_ReferenceLinePoint* mutable_poly_line(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::ReferenceLine_ReferenceLinePoint >*
      mutable_poly_line();
  private:
  const ::osi3::ReferenceLine_ReferenceLinePoint& _internal_poly_line(int index) const;
  ::osi3::ReferenceLine_ReferenceLinePoint* _internal_add_poly_line();
  public:
  const ::osi3::ReferenceLine_ReferenceLinePoint& poly_line(int index) const;
  ::osi3::ReferenceLine_ReferenceLinePoint* add_poly_line();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::ReferenceLine_ReferenceLinePoint >&
      poly_line() const;

  // .osi3.Identifier id = 1;
  bool has_id() const;
  private:
  bool _internal_has_id() const;
  public:
  void clear_id();
  const ::osi3::Identifier& id() const;
  ::osi3::Identifier* release_id();
  ::osi3::Identifier* mutable_id();
  void set_allocated_id(::osi3::Identifier* id);
  private:
  const ::osi3::Identifier& _internal_id() const;
  ::osi3::Identifier* _internal_mutable_id();
  public:
  void unsafe_arena_set_allocated_id(
      ::osi3::Identifier* id);
  ::osi3::Identifier* unsafe_arena_release_id();

  // @@protoc_insertion_point(class_scope:osi3.ReferenceLine)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::ReferenceLine_ReferenceLinePoint > poly_line_;
  ::osi3::Identifier* id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_osi_5freferenceline_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReferenceLine_ReferenceLinePoint

// .osi3.Vector3d world_position = 1;
inline bool ReferenceLine_ReferenceLinePoint::_internal_has_world_position() const {
  return this != internal_default_instance() && world_position_ != nullptr;
}
inline bool ReferenceLine_ReferenceLinePoint::has_world_position() const {
  return _internal_has_world_position();
}
inline const ::osi3::Vector3d& ReferenceLine_ReferenceLinePoint::_internal_world_position() const {
  const ::osi3::Vector3d* p = world_position_;
  return p != nullptr ? *p : reinterpret_cast<const ::osi3::Vector3d&>(
      ::osi3::_Vector3d_default_instance_);
}
inline const ::osi3::Vector3d& ReferenceLine_ReferenceLinePoint::world_position() const {
  // @@protoc_insertion_point(field_get:osi3.ReferenceLine.ReferenceLinePoint.world_position)
  return _internal_world_position();
}
inline void ReferenceLine_ReferenceLinePoint::unsafe_arena_set_allocated_world_position(
    ::osi3::Vector3d* world_position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(world_position_);
  }
  world_position_ = world_position;
  if (world_position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osi3.ReferenceLine.ReferenceLinePoint.world_position)
}
inline ::osi3::Vector3d* ReferenceLine_ReferenceLinePoint::release_world_position() {
  
  ::osi3::Vector3d* temp = world_position_;
  world_position_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::osi3::Vector3d* ReferenceLine_ReferenceLinePoint::unsafe_arena_release_world_position() {
  // @@protoc_insertion_point(field_release:osi3.ReferenceLine.ReferenceLinePoint.world_position)
  
  ::osi3::Vector3d* temp = world_position_;
  world_position_ = nullptr;
  return temp;
}
inline ::osi3::Vector3d* ReferenceLine_ReferenceLinePoint::_internal_mutable_world_position() {
  
  if (world_position_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::Vector3d>(GetArena());
    world_position_ = p;
  }
  return world_position_;
}
inline ::osi3::Vector3d* ReferenceLine_ReferenceLinePoint::mutable_world_position() {
  // @@protoc_insertion_point(field_mutable:osi3.ReferenceLine.ReferenceLinePoint.world_position)
  return _internal_mutable_world_position();
}
inline void ReferenceLine_ReferenceLinePoint::set_allocated_world_position(::osi3::Vector3d* world_position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(world_position_);
  }
  if (world_position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(world_position)->GetArena();
    if (message_arena != submessage_arena) {
      world_position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, world_position, submessage_arena);
    }
    
  } else {
    
  }
  world_position_ = world_position;
  // @@protoc_insertion_point(field_set_allocated:osi3.ReferenceLine.ReferenceLinePoint.world_position)
}

// double s_position = 2;
inline void ReferenceLine_ReferenceLinePoint::clear_s_position() {
  s_position_ = 0;
}
inline double ReferenceLine_ReferenceLinePoint::_internal_s_position() const {
  return s_position_;
}
inline double ReferenceLine_ReferenceLinePoint::s_position() const {
  // @@protoc_insertion_point(field_get:osi3.ReferenceLine.ReferenceLinePoint.s_position)
  return _internal_s_position();
}
inline void ReferenceLine_ReferenceLinePoint::_internal_set_s_position(double value) {
  
  s_position_ = value;
}
inline void ReferenceLine_ReferenceLinePoint::set_s_position(double value) {
  _internal_set_s_position(value);
  // @@protoc_insertion_point(field_set:osi3.ReferenceLine.ReferenceLinePoint.s_position)
}

// -------------------------------------------------------------------

// ReferenceLine

// .osi3.Identifier id = 1;
inline bool ReferenceLine::_internal_has_id() const {
  return this != internal_default_instance() && id_ != nullptr;
}
inline bool ReferenceLine::has_id() const {
  return _internal_has_id();
}
inline const ::osi3::Identifier& ReferenceLine::_internal_id() const {
  const ::osi3::Identifier* p = id_;
  return p != nullptr ? *p : reinterpret_cast<const ::osi3::Identifier&>(
      ::osi3::_Identifier_default_instance_);
}
inline const ::osi3::Identifier& ReferenceLine::id() const {
  // @@protoc_insertion_point(field_get:osi3.ReferenceLine.id)
  return _internal_id();
}
inline void ReferenceLine::unsafe_arena_set_allocated_id(
    ::osi3::Identifier* id) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(id_);
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:osi3.ReferenceLine.id)
}
inline ::osi3::Identifier* ReferenceLine::release_id() {
  
  ::osi3::Identifier* temp = id_;
  id_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::osi3::Identifier* ReferenceLine::unsafe_arena_release_id() {
  // @@protoc_insertion_point(field_release:osi3.ReferenceLine.id)
  
  ::osi3::Identifier* temp = id_;
  id_ = nullptr;
  return temp;
}
inline ::osi3::Identifier* ReferenceLine::_internal_mutable_id() {
  
  if (id_ == nullptr) {
    auto* p = CreateMaybeMessage<::osi3::Identifier>(GetArena());
    id_ = p;
  }
  return id_;
}
inline ::osi3::Identifier* ReferenceLine::mutable_id() {
  // @@protoc_insertion_point(field_mutable:osi3.ReferenceLine.id)
  return _internal_mutable_id();
}
inline void ReferenceLine::set_allocated_id(::osi3::Identifier* id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(id_);
  }
  if (id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(id)->GetArena();
    if (message_arena != submessage_arena) {
      id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    
  } else {
    
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:osi3.ReferenceLine.id)
}

// repeated .osi3.ReferenceLine.ReferenceLinePoint poly_line = 2;
inline int ReferenceLine::_internal_poly_line_size() const {
  return poly_line_.size();
}
inline int ReferenceLine::poly_line_size() const {
  return _internal_poly_line_size();
}
inline void ReferenceLine::clear_poly_line() {
  poly_line_.Clear();
}
inline ::osi3::ReferenceLine_ReferenceLinePoint* ReferenceLine::mutable_poly_line(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.ReferenceLine.poly_line)
  return poly_line_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::ReferenceLine_ReferenceLinePoint >*
ReferenceLine::mutable_poly_line() {
  // @@protoc_insertion_point(field_mutable_list:osi3.ReferenceLine.poly_line)
  return &poly_line_;
}
inline const ::osi3::ReferenceLine_ReferenceLinePoint& ReferenceLine::_internal_poly_line(int index) const {
  return poly_line_.Get(index);
}
inline const ::osi3::ReferenceLine_ReferenceLinePoint& ReferenceLine::poly_line(int index) const {
  // @@protoc_insertion_point(field_get:osi3.ReferenceLine.poly_line)
  return _internal_poly_line(index);
}
inline ::osi3::ReferenceLine_ReferenceLinePoint* ReferenceLine::_internal_add_poly_line() {
  return poly_line_.Add();
}
inline ::osi3::ReferenceLine_ReferenceLinePoint* ReferenceLine::add_poly_line() {
  // @@protoc_insertion_point(field_add:osi3.ReferenceLine.poly_line)
  return _internal_add_poly_line();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::osi3::ReferenceLine_ReferenceLinePoint >&
ReferenceLine::poly_line() const {
  // @@protoc_insertion_point(field_list:osi3.ReferenceLine.poly_line)
  return poly_line_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osi3

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_osi_5freferenceline_2eproto
